# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 925dea7db17fef287ca4063097b187ce80f485fd82d86e1be888652e256634ea5d08d833b079f8ddb5518042467f12b27f0e4371a015f3ae6e77e3a0036115b7

test:
  secret_key_base: 85e5b220c1df64f3335d5b8d0f2dd9994713bfcf6259db33d93690c202d333acc1b9f1da357a7d3d1f57ea7becfc41b4ef7a54c9d81cb8c21cc9f807c329e4f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
